name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/ci.yaml
      - app/**

env:
  IMAGE_REF: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

jobs:
  build:
    runs-on: ci-docker-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: scan dockerfile
      run: |
        trivy config \
        --severity HIGH,CRITICAL \
        --file-patterns "dockerfile:Dockerfile" .


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .

    - name: Save Docker image as artifact
      run: docker save ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} -o nginx-image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: nginx-image.tar


  scan_trivy:
    runs-on: ci-docker-runner
    needs: build
    steps:
        - name: Download Docker image artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-image

        - name: Load Docker image
          run: docker load -i nginx-image.tar

        - name: Run Trivy scan
          run: |
            trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

  push_image:
    runs-on: ci-docker-runner
    needs: scan_trivy
    steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Download Docker image artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-image

        - name: Load Docker image
          run: docker load -i image.tar

        - name: Push Docker image to Docker Hub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}


  
  
      