name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - ci.yaml

jobs:
  build:
    runs-on: ci-docker-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: scan dockerfile
      run: |
        trivy config \
        --severity HIGH,CRITICAL \
        --file-patterns "dockerfile:Dockerfile" .


    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .


  scan_trivy:
    runs-on: ci-docker-runner
    needs: build
    steps:
        - name: Run Trivy scan
          run: |
            trivy image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

  push_image:
    runs-on: ci-docker-runner
    needs: scan_trivy
    steps:
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Docker image to Docker Hub
          run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}


  
  
      